name: mood_path
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

    # Supabase (Database + Auth)
  supabase_flutter: ^2.3.0
  # State Management (MVVM)
  provider: ^6.1.1
  # API calls (Claude)
  http: ^1.1.0
  # Secure API key storage
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
